---
- hosts: localhost
  vars: 
    - cu_id: 77555
  tasks:
    - name: Atlantic_Net Cloud - Create new server
      atlantic_cloud:
         state: present
         public_key: ATL8f59337f60fb45e4ff600c38e62ab540
         private_key: 66f002a2b6c5d742a9ce6d6e4de333534c73b128
         servername: "test-orl-elasticstack"
         vm_location: USEAST1
         imageid: CentOS-7.3_64bit
         planname: "G2.4GB"
         ssh_key: "ansible"
      register: elasticstack

    - name: Adding the new hosts to the host file
      add_host:
        name: "{{ item.name.results.ip_address }}"
        groups: "{{ item.groups }}"
      with_items:
        - { name: "{{elasticstack}}", groups: 'elk'}

    - name: Sending info to file
      template: src=templates/new_elasticstack.j2 dest=/etc/ansible/new_server_{{elasticstack.results.cu_id}} owner=root group=root mode=644

    - name: Waiting for servers to come online...
      local_action:
        module: wait_for
          host={{ elasticstack.results.ip_address }}
          port=22
          delay=1
          timeout=300

- hosts: elk
  pre_tasks:
    - name: Update distro
      yum:
        state: latest 
        name: '*'
        update_cache: yes
    - name: Remove firewalld
      yum:
        state: absent
        name: firewalld
    - name: Install iptables-services
      yum:
        state: present
        name: iptables-services
    - name: Start iptables
      systemd:
        name: iptables
        state: started
        enabled: yes
  roles: 
    - derek.elk
  
