---
- hosts: localhost
  vars: 
    - cu_id: 77555
  tasks:
    - name: Atlantic_Net Cloud - Create new server
      atlantic_cloud:
         state: present
         public_key: ATL8f59337f60fb45e4ff600c38e62ab540
         private_key: 66f002a2b6c5d742a9ce6d6e4de333534c73b128
         servername: "Graylog-test"
         vm_location: USEAST1
         imageid: debian-8.8.0_64bit
         planname: "G2.4GB"
         ssh_key: "ansible"
      register: elasticstack

    - name: Adding the new hosts to the host file
      add_host:
        name: "{{ item.name.results.ip_address }}"
        groups: "{{ item.groups }}"
      with_items:
        - { name: "{{elasticstack}}", groups: 'elk'}

    - name: Sending info to file
      template: src=templates/new_elasticstack.j2 dest=/etc/ansible/new_server_{{elasticstack.results.cu_id}} owner=root group=root mode=644

    - name: Waiting for servers to come online...
      local_action:
        module: wait_for
          host={{ elasticstack.results.ip_address }}
          port=22
          delay=20
          timeout=300

- hosts: elk
  vars:
    # Graylog2 is not compatible with elasticsearch 5.x, so ensure to use 2.x (graylog3 will be compatible)
    # Also use version 0.2 of elastic.elasticsearch (ansible role), because vars are different
    es_major_version: "2.x"
    es_version: "2.4.3"

    es_instance_name: 'graylog'
    es_scripts: False
    es_templates: False
    es_version_lock: False
    es_heap_size: 1g

    es_config: {
      node.name: "graylog",
      cluster.name: "graylog",
      discovery.zen.ping.unicast.hosts: "localhost:9301",
      http.port: 9200,
      transport.tcp.port: 9300,
      network.host: 0.0.0.0,
      node.data: true,
      node.master: true,
      bootstrap.mlockall: false,
      discovery.zen.ping.multicast.enabled: false
    }

    # Do not set web_endpoint_uri to choose the first ip address available automatically
    graylog_web_endpoint_uri: ''
    # Option 2:
    # graylog_web_endpoint_uri: 'http://{{ ansible_host }}:9000/api/'
    # Note: if you set here localhost or 127.0.0.1 the web interface will never reach your webui as client
    # runs with javascript on your browser since graylog 2.0

  pre_tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
    - name: Update VMs
      apt:
        update_cache: yes
        upgrade: yes
        state: latest
    - name: IPTABLES || Install iptables service (netfilter-persistent)
      apt:
        name: netfilter-persistent
        state: latest
    - name: Started netfilter-persistent
      systemd:
        name: netfilter-persistent
        state: started
        enabled: yes
  roles:
    - atlantic-ids
  
