---
- hosts: localhost
  vars:
    - cu_id: 77555
    - datacenter: USEAST1
    - public_key: ATL8f59337f60fb45e4ff600c38e62ab540
    - private_key: 66f002a2b6c5d742a9ce6d6e4de333534c73b128
    - ssh_key: "ansible"
    - builds:
        - build: host
          imageid: ubuntu-16.04_64bit
          planname: "G2.2GB"
          trendmicro: yes
          backups: cloud
    - firewall: yes
      private_range: 10.83.61.0/25
      vpn_range: 10.83.61.128/25
      psk: 6psnGMs-7!@RZ3sgr_6hcE9ReuSgarZt4z?UEX%*hK26_A_5-t-s4a6=
      identifier: DerekDesigns
    - ids: yes
        # - build: ids
        #   imageid: CentOS-7.3_64bit
        #   planname: "G2.2GB"

  roles:
    - atlantic-cloud
  
- hosts: derek-host
  vars:
  pre_tasks:
    - name: Install aptitude (Debian and Ubuntu)
      apt:
        name: aptitude
        state: latest
      when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

    - name: Update VMs (Debian and Ubuntu)
      apt:
        update_cache: yes
        upgrade: yes
        state: latest
      when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
    
    - name: Update VMs (Centos)
      yum:
        update_cache: yes
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"
  
  roles:
    - atlantic.iptables
    - atlantic.snmp 

