- name: Install snmpd (Ubuntu or Debian)
  apt:
    name: snmpd
    state: latest
  when: ansible_distribution == "Debian" || ansible_distribution == "Ubuntu"

- name: SNMPD || Install snmpd (Centos)
  yum:
    name: net-snmp 
    state: latest
  when: ansible_os_family == "RedHat"

- name: Copy default snmpd.conf
  template:
    src: templates/snmpd.conf.j2
    dest: /etc/snmp/snmpd.conf
    force: yes
    
- name: Enable and restart snmpd
  systemd:
    name: snmpd
    enabled: yes
    state: restarted