---
- name: redhat | installing apache
  dnf:
    name: "httpd"
    state: present
  when: >
        ansible_distribution == "Fedora"

- name: redhat | installing apache
  yum:
    name: "httpd"
    state: present
  when: >
        ansible_distribution != "Fedora"

- name: redhat | enabling apache on boot and starting
  service:
    name: "httpd"
    state: started
    enabled: yes
