---
- name: Add r1soft repo
  raw: echo deb http://repo.r1soft.com/apt stable main >> /etc/apt/sources.list
- name: Get r1soft key
  raw: wget http://repo.r1soft.com/r1soft.asc
- name: Add r1soft key
  raw: apt-key add /root/r1soft.asc
- name: Install r1soft agent
  apt:
    name: r1soft-cdp-enterprise-agent
    update_cache: yes
    state: latest
#    - name: Get the r1soft key from server
#      raw: r1soft-setup --get-key https://cdp.dal-tx.atlantic.net
- name: Enable and restart cdp-agent
  systemd:
    name: cdp-agent
    enabled: yes
    state: restarted   