---
# handlers file for ansible-mysql
- name: "restart mariadb"
  service:
    name: "mariadb"
    state: "restarted"

- name: "restart mysql"
  service:
    name: "mysql"
    state: "restarted"

- name: "reload mysql"
  service:
    name: "mysql"
    state: "reloaded"
