---
- name: redhat | installing pre-reqs
  yum:
    name: "{{ item }}"
    state: "present"
  with_items:
    - 'MySQL-python'
  when: ansible_distribution_release != "Fedora"

- name: redhat | installing mysql CentOS 6
  yum:
    name: "{{ item }}"
    state: "present"
  with_items:
    - 'mysql-server'
    - 'mysql'
  when: >
        ansible_distribution_release != "Fedora" and
        (ansible_distribution_version < '7')

- name: redhat | enabling on boot and start CentOS 6
  service:
    name: "mysqld"
    state: "started"
    enabled: yes
  when: (ansible_distribution_version < '7')

- name: redhat | installing mariadb mysql CentOS 7
  yum:
    name: "{{ item }}"
    state: "present"
  register: "mariadb_server_installed"
  with_items:
    - 'mariadb-server'
    - 'mariadb'
  when: >
        ansible_distribution_release != "Fedora" and
        (ansible_distribution_version >= '7')

- name: redhat | enabling on boot and start CentOS 7
  service:
    name: "mariadb"
    state: "started"
    enabled: yes
  when: (ansible_distribution_version >= '7')

- name: redhat | configuring mysql
  template:
    src: "etc/my.cnf.j2"
    dest: "/etc/my.cnf"
    owner: "root"
    group: "root"
    mode: 0644
  register: "mariadb_reconfigured_redhat"
  notify: "restart mariadb"
  when: >
        ansible_distribution_release != "Fedora" and
        (ansible_distribution_version >= '7')
