---
- debug:
    msg: "{{item}}"
  with_items: 
    - "{{builds}}"

- name: "Atlantic_Net Cloud - Creating hosts"
  atlantic_cloud:
      state: present
      public_key: "{{ public_key }}"
      private_key: "{{ private_key }}"
      servername: "{{cu_id}}-{{datacenters[datacenter]}}-{{item.build}}"
      vm_location: "{{ datacenter }}"
      imageid: "{{ item.imageid }}"
      planname: "{{ item.planname }}"
      ssh_key: "{{ ssh_key }}"
      enablebackup: '{{ backup_options[item.backups | default("N")]}}'
  with_items: "{{ builds }}"
  register: cloudserver_hosts

- name: "Atlantic_Net Cloud - Creating firewall"
  atlantic_cloud:
      state: present
      public_key: "{{ public_key }}"
      private_key: "{{ private_key }}"
      servername: "{{cu_id}}-{{datacenters[datacenter]}}-fw"
      vm_location: "{{ datacenter }}"
      imageid: "FreeBSD-10.1-pfsense_64bit"
      planname: "G2.2GB"
      ssh_key: "{{ ssh_key }}"
      enablebackup: 'Y'
  when: firewall
  register: cloudserver_ids

- name: "Atlantic_Net Cloud - Creating IDS"
  atlantic_cloud:
      state: present
      public_key: "{{ public_key }}"
      private_key: "{{ private_key }}"
      servername: "{{cu_id}}-{{datacenters[datacenter]}}-ids"
      vm_location: "{{ datacenter }}"
      imageid: "CentOS-6.9_64bit"
      planname: "G2.2GB"
      ssh_key: "{{ ssh_key }}"
      enablebackup: 'Y'
  when: ids
  register: cloudserver_firewall

- debug:
    msg: "{{item}}"
  with_items: 
    - "{{cloudserver_hosts}}"
    - "{{cloudserver_ids}}"
    - "{{cloudserver_firewall}}"

# - debug:
#     msg: "{{item}}"
#   with_nested:
#     - "{{cloudservers.results}}"
#     - results

- name: Adding the new host to the dynamic host file
  add_host:
    name: "{{ item.results.ip_address }}"
    groups: "cloud_{{item.item.build}}"
    when: (item.results.vm_image != "firewall") and (item.results.vm_image != "ubuntu-16.04_64bit") 
  with_items:
    - "{{cloudserver_hosts}}"

- name: Adding the new host to the dynamic host file (Ubuntu 16)
  add_host:
    name: "{{ item.results.ip_address }}"
    ansible_python_interpreter: /usr/bin/python3
    groups: "cloud_{{item.item.build}}"
  when: item.results.vm_image == "ubuntu-16.04_64bit"
  with_items:
    - "{{cloudserver_hosts}}"

- name: Adding the new host to the dynamic host file (IDS)
  add_host:
    name: "{{ item.results.ip_address }}"
    groups: "cloud_ids"
  when: ids
  with_items:
    - "{{cloudserver_ids}}"

- name: Adding the new host to the dynamic host file (Firewall)
  add_host:
    name: "{{ item.results.ip_address }}"
    ansible_python_interpreter: /usr/local/bin/python2.7
    ansible_ssh_pass: "Nrprocks!"
    groups: "cloud_firewall"
  when: firewall
  with_items:
    - "{{cloudserver_firewall}}"

- set_fact:
    gateway: "{{item.results.vm_ip_gateway}}"
    cidr: "{{ '{{ item.results.vm_ip_address }}/{{ item.results.vm_ip_subnet }}' | ipaddr('prefix') }}"
    fw_ip_address: "{{ item.results.vm_ip_address}}"
  when: firewall
  with_items:
    - "{{cloudserver_firewall}}"

- name: Sending info to file
  template: src=templates/new_cloudservers.j2 dest=/etc/ansible/{{cu_id}}_new_order owner=root group=root mode=644

- name: Waiting for server to come online...
  local_action:
    module: wait_for
      host={{ item.0.results.ip_address }}
      port=22
      delay=20
      timeout=300
  with_nested:
    - "{{cloudservers.results}}"
    - results
