#!/bin/sh

PATH=/usr/bin:/bin:/usr/sbin:/sbin
WORK=`mktemp /tmp/smart.XXXXXXXX`

fail=0

for disk in `grep -e ' [hs]d[a-z]$' /proc/partitions | awk '{print $4}'`
do
	dev="/dev/$disk"

	rm -f $WORK
	smartctl -H $dev 2>&1 > $WORK
	rv=$(($? & 24))

	printf "%s: " $dev
	if ! grep result $WORK
	then
		cat $WORK
	fi

	if [ $rv -gt 0 ]
	then
		fail=1
	fi
done

rm $WORK
exit $fail