#!/bin/sh
CONT="a0"
STATUS=0
MEGACLI=/opt/MegaRAID/MegaCli/MegaCli64
WORK=`mktemp /tmp/megaraid.XXXXXXXXX`

echo -n "Checking RAID status on "
hostname
for a in $CONT
do

$MEGACLI -AdpAllInfo -$a | grep "Product Name"
# | cut -d: -f2
noonline=`$MEGACLI PDList -$a | grep Online | wc -l`
echo "No of Physical disks online : $noonline"
$MEGACLI -AdpAllInfo -a0 | grep "Degraded"
$MEGACLI -AdpAllInfo -a0 | grep "Failed Disks"
$MEGACLI -AdpAllInfo -a0 | grep "Failed Disks" | awk '{print $4}' | tee $WORK
grep -q '0' $WORK
rv=$?

done

rm $WORK
mv /root/MegaSAS.log /root/MegaSASraid.log
exit $rv