---
- include: debian.yml
  when: ansible_distribution == "Debian" || ansible_distribution == "Ubuntu"

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- include: disable-other-firewalls.yml