---
- hosts: client133162
  vars:
  tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
    - name: Update VMs
      apt:
        update_cache: yes
        upgrade: yes
        state: latest
    - name: Install iptables service (netfilter-persistent)
      apt:
        name: netfilter-persistent
        state: latest
    - name: Stop netfilter-persistent
      systemd:
        name: netfilter-persistent
        state: stopped
    - name: Rename netfilter-persistent.service to iptables.service
      command: mv /lib/systemd/system/netfilter-persistent.service /lib/systemd/system/iptables.service
      ignore_errors: yes
    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes
        name: iptables
        enabled: yes
        state: started
    - name: Make /etc/iptables directory
      file:
        path: /etc/iptables
        state: directory
    - name: Copy IPv4 plugin for netfilter
      copy:
        src: templates/15-ip4tables
        dest: /usr/share/netfilter-persistent/plugins.d/15-ip4tables
        mode: a+x
    - name: Copy iptables template
      copy:
        src: templates/iptables
        dest: /etc/iptables/rules.v4
    - name: Restore from /etc/iptables
      raw: iptables-restore < /etc/iptables/rules.v4
    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes
        name: iptables
        enabled: yes
        state: started
    - name: Install snmpd
      apt:
        name: snmpd
        state: latest
    - name: Copy default snmpd.conf 
      copy:
        src: templates/snmpd.conf
        dest: /etc/snmp/snmpd.conf
        force: yes
    - name: Enable and restart snmpd
      systemd:
        name: snmpd
        enabled: yes
        state: restarted
    - name: Add r1soft repo
      raw: echo deb http://repo.r1soft.com/apt stable main >> /etc/apt/sources.list
    - name: Get r1soft key
      raw: wget http://repo.r1soft.com/r1soft.asc
    - name: Add r1soft key
      raw: apt-key add /root/r1soft.asc
    - name: Install r1soft agent
      apt:
        name: r1soft-cdp-enterprise-agent
        update_cache: yes
        state: latest
    - name: Get the r1soft key from server
      raw: r1soft-setup --get-key https://cdp.dal-tx.atlantic.net
    - name: Enable and restart cdp-agent
      systemd:
        name: cdp-agent
        enabled: yes
        state: restarted
      
