---
- hosts: client133159
  vars:
  tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
    - name: Update VMs
      apt:
        update_cache: yes
        upgrade: yes
        state: latest
    - name: Install iptables service (netfilter-persistent)
      apt:
        name: netfilter-persistent
        state: latest
    - name: Stop netfilter-persistent
      systemd:
        name: netfilter-persistent
        state: stopped
    - name: Rename netfilter-persistent.service to iptables.service
      command: mv /lib/systemd/system/netfilter-persistent.service /lib/systemd/system/iptables.service
      ignore_errors: yes
    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes
        name: iptables
        enabled: yes
        state: started
    - name: Copy iptables template
      copy:
        src: templates/iptables
        dest: /etc/iptables
    - name: Restore from /etc/iptables
      raw: iptables-restore < /etc/iptables
