---
- hosts: client133898-fw
  gather_facts: no
  vars:
    device_id: 21666-2275
    hostname: 21666-2275
    wan_ip: 45.58.40.189
    wan_cidr: 24
    gateway: 45.58.40.1
    lan_ip: 10.112.50.1
    lan_range: 10.112.50.0/25
    lan_cidr: 25
    vpn_range: 10.112.50.128/25
    ids: yes
    ids_ip: 10.112.50.2
    wan_interface: vtnet0
    lan_interface: vtnet1
  vars_prompt:
    - name: "adminpassword"
      prompt: "Administrator password please"
      private: yes
      encrypt: "bcrypt"
      confirm: yes
  tasks:
#    - name: Add Ansible control IP to the rules
#      raw: easyrule pass wan tcp 104.245.39.134 {{ wan_ip }} 22
#    - name: Fetch the latest version
#      raw: fetch https://updates.pfsense.org/_updaters/amd64/latest.tgz
#    - name: Upgrade pfSense
#      raw: /etc/rc.firmware pfSenseupgrade /root/latest.tgz
#    - name: Wait for reboot
#      wait_for:
#        host: "{{ ansible_host|default(ansible_ssh_host|default(inventory_hostname)) }}"
#        port: 22
#        delay: 60
#        connection: local
#    need to have some kind of wait here so pfctl can be disabled again. or something added beforehand
    - name: Install packages
      pkgng:
        name: net-snmp,xmlstarlet,sudo,nano,rsync,php56-openssl
        state: present
    - name: Copy snmpd.conf over
      template:
        src: templates/snmpd.conf.j2
        dest: /usr/local/share/snmp/snmpd.conf
    - name: Copy config.xml over (cross fingers)
      template:
        src: templates/config.xml.j2
        dest: /cf/conf/config.xml
    - name: Remove config temp file
      raw: rm -f /tmp/config.cache && /etc/rc.reload_all start
