---
- hosts: localhost
  vars: 
    - cu_id: 77555
  tasks:
    - name: Atlantic_Net Cloud - Create new server
      atlantic_cloud:
         state: present
         public_key: ATL8f59337f60fb45e4ff600c38e62ab540
         private_key: 66f002a2b6c5d742a9ce6d6e4de333534c73b128
         servername: "{{cu_id}}-orl-ghostserver"
         vm_location: USEAST1
         imageid: ubuntu-14.04_64bit
         planname: "G2.2GB"
         ssh_key: "ansible"
      register: ghostserver

    - name: Adding the new hosts to the host file
      add_host:
        name: "{{ item.name.results.ip_address }}"
        groups: "{{ item.groups }}"
      with_items:
        - { name: "{{ghostserver}}", groups: 'ghost'}

    - name: Sending info to file
      template: src=templates/new_ghostserver.j2 dest=/etc/ansible/new_server_{{ghostserver.results.cu_id}} owner=root group=root mode=644

    - name: Waiting for servers to come online...
      local_action:
        module: wait_for
          host={{ ghostserver.results.ip_address }}
          port=22
          delay=1
          timeout=300

- hosts: ghost
  pre_tasks:
    - name: Update distro
      apt:
        state: latest 
        upgrade: full
        update_cache: yes
    - name: Install unzip
      apt:
        name: unzip
        state: present
  roles:
    - geerlingguy.nodejs
  post_tasks:
    - name: Create /var/www/ghost
      file:
        path: /var/www/ghost
        state: directory
    - name: Curl ghost
      get_url:
        url: https://ghost.org/zip/ghost-latest.zip
        dest: /root/ghost.zip
    - name: Unzip ghost into /var/www/ghost
      unarchive:
        src: /root/ghost.zip
        dest: /var/www/ghost
        remote_src: yes
    - name: NPM install ghost
      npm:
        path: /var/www/ghost
