---
- hosts: localhost
  vars: 
    - cu_id: 77555
  tasks:
    - name: Atlantic_Net Cloud - Create new server
      atlantic_cloud:
         state: present
         public_key: ATL8f59337f60fb45e4ff600c38e62ab540
         private_key: 66f002a2b6c5d742a9ce6d6e4de333534c73b128
         servername: "{{cu_id}}-orl-percona1"
         vm_location: USEAST1
         imageid: ubuntu-16.04_64bit
         planname: "G2.2GB"
         ssh_key: "ansible"
      register: cloud1

    - name: Atlantic_Net Cloud - Create new server
      atlantic_cloud:
         state: present
         public_key: ATL8f59337f60fb45e4ff600c38e62ab540
         private_key: 66f002a2b6c5d742a9ce6d6e4de333534c73b128
         servername: "{{cu_id}}-orl-percona2"
         vm_location: USEAST1
         imageid: ubuntu-16.04_64bit
         planname: "G2.2GB"
         ssh_key: "ansible"
      register: cloud2

 
