---
- hosts: pfsense
  gather_facts: no
  vars:
    hostname: "{{ansible_hostname}}"
    wan_ip: 209.208.111.157 
    wan_cidr: 22
    gateway: 209.208.108.1
    lan_ip: 10.83.61.1
    lan_range: 10.83.61.0/25
    lan_cidr: 24
    vpn_range: 10.83.61.128/25
    ids: yes
    ids_ip: 10.83.61.2
    wan_interface: vtnet0
    lan_interface: vtnet1
  vars_prompt:
    - name: "adminpassword"
      prompt: "Administrator password please"
      private: yes
      encrypt: "bcrypt"
      confirm: yes 
  tasks:
    - name: Fetch the latest version
      raw: fetch https://updates.pfsense.org/_updaters/amd64/latest.tgz
    - name: Upgrade pfSense
      raw: /etc/rc.firmware pfSenseupgrade /root/latest.tgz
#    need to have some kind of wait here so pfctl can be disabled again. or something added beforehand
    - name: Install packages
      pkgng:
        name: net-snmp,xmlstarlet,sudo,nano,rsync,php56-openssl
        state: present 
    - name: Copy snmpd.conf over
      template:
        src: templates/snmpd.conf.j2
        dest: /usr/local/share/snmp/snmpd.conf
    - name: Copy config.xml over (cross fingers)
      template:
        src: templates/config.xml.j2
        dest: /cf/conf/config.xml        
    - name: Remove config temp file
      raw: rm -f /tmp/config.cache && /etc/rc.reload_all start
    - name: Change root password
      raw: echo "{{ adminpassword }}" | pw usermod root -h 0
