---
- hosts: all
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  tasks:
  - name: Upgrade all packages
    yum:
        name='*'
        state=latest
  - name: Install default packages
    yum:
        name={{item}}
        state=latest
    with_items:
      - python
      - iptables
      - iptables-services
      - net-snmp
  - name: Install apache package
    yum:
        name=httpd
        state=latest
  - name: Ensure apache is running (and enable it at boot)
    service:
        name=httpd
        state=started
        enabled=yes
  - name: Ensure snmpd is running (and enable it at boot)
    service: 
        name=snmpd 
        state=started
        enabled=yes
    notify: Restart snmpd
  - name: Template snmpd.conf
    template: src=templates/snmpd.conf.j2 dest=/etc/snmp/snmpd.conf owner=root group=root mode=644 backup=yes
    notify: Restart snmpd
  handlers:
    - name: Restart apache
      service:
        name=httpd
        state=restarted
    - name: Restart snmpd
      service:
         name=snmpd
         state=restarted

- hosts: snorby
  roles:
    - role: ansible-ntp
    - role: ansible-apache2
      when: passenger_webserver == "apache2"
    - role: ansible-passenger
    - role: ansible-mysql
    - role: ansible-snort
    - role: ansible-snorby