---
    # Build Types:
    # ====================
    # 'host', 'firewall', or 'ids'

    # Cloud User ID
    
    # Server Name

    # OSes: 
    # ====================
    # arch-2016.03.01_64bit
    # CentOS-6.9_32bit, CentOS-6.9_64bit
    # CentOS-7.2-cPanel_64bit, CentOS-7.3_64bit
    # debian-7.11.0_32bit, debian-7.11.0_64bit
    # debian-8.8.0_32bit, debian-8.8.0_64bit
    # debian-9.0.0_32bit, debian-9.0.0_64bit
    # Fedora-24_64bit, Fedora-25_64bit
    # FreeBSD-10.3_64bit, FreeBSD-11.0_64bit
    # ubuntu-14.04_32bit, ubuntu-14.04_64bit
    # ubuntu-14.04-docker_64bit, ubuntu-14.04-lamp_64bit
    # ubuntu-14.04-lemp_64bit, ubuntu-14.04-nodejs_64bit
    # ubuntu-14.04-octobercms_64bit, ubuntu-14.04-wordpress_64bit
    # ubuntu-16.04_32bit, ubuntu-16.04_64bit
    # ubuntu-16.10_32bit, ubuntu-16.10_64bit
    # Windows-2008-R2-SP1-Datacenter_64bit
    # Windows-2012-R2-Datacenter_64bit
    # Windows-2012-R2-Datacenter-Desktop_64bit
    # Windows-2016-Datacenter_64bit
    # Windows-2016-Datacenter-Containers_64bit
    # ### FreeBSD-10.1-pfsense_64bit ###
    #

    # Datacenters:
    # ====================
    # USEAST1 is Orlando, FL
    # USEAST2 is New York City, NY
    # USCENTRAL1 is Dallas, TX;
    # USWEST1 is San Francisco, CA;
    # CAEAST1 is Toronto, ON;
    # EUWEST1 is London, UK.

    # Plans:
    # =====================
    # S2.16GB, S2.32GB, S2.64GB, S2.96GB, S2.128GB 
    # M2.16GB, M2.32GB, M2.64GB, M2.128GB
    # C2.8GB, C2.16GB, C2.32GB, C2.64GB 
    # G2.512MB, G2.1GB, G2.2GB, G2.4GB, 
    # G2.8GB, G2.16GB, G2.32GB, G2.64GB

- hosts: localhost
  vars:
    - cu_id: 77755
    - sshkey: ansible
    - publickey: ATL8f59337f60fb45e4ff600c38e62ab540
    - privatekey: 66f002a2b6c5d742a9ce6d6e4de333534c73b128

  roles:
    - role: atlantic-cloud
      build_type: host
      servername: "{{cu_id}}_orl_{{build_type}}_01"
      os: ubuntu-16.04_64bit
      datacenter: USEAST1
      plan: G2.2GB
    - role: atlantic-cloud
      build_type: ids
      servername: "{{cu_id}}_orl_{{build_type}}_01"
      os: debian-8.8.0_64bit
      datacenter: USEAST1
      plan: G2.2GB
    - role: atlantic-cloud
      build_type: firewall
      servername: "{{cu_id}}_orl_{{build_type}}_01"
      os: FreeBSD-10.1-pfsense_64bit
      datacenter: USEAST1
      plan: G2.2GB

- hosts: cloud_host
  roles:
    - atlantic-host

- hosts: cloud_firewall
  gather_facts: no
  vars:
    #firewall section
    - wan_ip: "{{ ip_address }}"
    - wan_cidr: "{{ cidr }}"
    - gateway: "{{ gateway }}"
    - lan_ip: 10.83.61.1
    - lan_range: 10.83.61.0/25
    - lan_cidr: 24
    - vpn_range: 10.83.61.128/25
  vars_prompt:
    - name: "adminpassword"
      prompt: "Administrator password please"
      private: yes
      encrypt: "bcrypt"
      confirm: yes
  roles:
    - atlantic-firewall

- hosts: cloud_ids
  vars:
    # Graylog2 is not compatible with elasticsearch 5.x, so ensure to use 2.x (graylog3 will be compatible)
    # Also use version 0.2 of elastic.elasticsearch (ansible role), because vars are different
    es_major_version: "2.x"
    es_version: "2.4.3"

    es_instance_name: 'graylog'
    es_scripts: False
    es_templates: False
    es_version_lock: False
    es_heap_size: 1g

    es_config: {
      node.name: "graylog",
      cluster.name: "graylog",
      discovery.zen.ping.unicast.hosts: "localhost:9301",
      http.port: 9200,
      transport.tcp.port: 9300,
      network.host: 0.0.0.0,
      node.data: true,
      node.master: true,
      bootstrap.mlockall: false,
      discovery.zen.ping.multicast.enabled: false
    }

    # Do not set web_endpoint_uri to choose the first ip address available automatically
    graylog_web_endpoint_uri: ''
    # Option 2:
    # graylog_web_endpoint_uri: 'http://{{ ansible_host }}:9000/api/'
    # Note: if you set here localhost or 127.0.0.1 the web interface will never reach your webui as client
    # runs with javascript on your browser since graylog 2.0
  pre_tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
    - name: Update VMs
      apt:
        update_cache: yes
        upgrade: yes
        state: latest
    - name: IPTABLES || Install iptables service (netfilter-persistent)
      apt:
        name: netfilter-persistent
        state: latest
    - name: Started netfilter-persistent
      systemd:
        name: netfilter-persistent
        state: started
        enabled: yes

  roles:
    - atlantic-ids

